version: 2
updates:
  - package-ecosystem: npm
    target-branch: "next"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "swagger-editor@next"
      - "cat: dependencies"
      - "javascript"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 3

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    target-branch: "next"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    target-branch: "next"
    directory: "/"
    schedule:
      interval: "weekly"
