version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 3
    ignore:
      # node-fetch must be synced manually
      - dependency-name: "node-fetch"
      - dependency-name: "release-it"
      - dependency-name: "@release-it/conventional-changelog"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  ######################
  # SwaggerEditor@next #
  ######################

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    target-branch: "next"
    labels:
      - "swagger-editor@next"
      - "cat: dependencies"
      - "javascript"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 3
    ignore:
      # do not update react-scripts as we use forked version of Create React App via git submodule
      - dependency-name: "create-react-app/packages/react-scripts"
      - dependency-name: "react-scripts"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    target-branch: "next"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    labels:
      - "swagger-editor@next"
      - "cat: dependencies"
      - "cat: docker"
      - "docker"

  - package-ecosystem: "github-actions"
    target-branch: "next"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "swagger-editor@next"
      - "cat: dependencies"
      - "github_actions"


