sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs' # protractor is unstable with iojs
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm@2
  - npm cache clean
  - npm install
  - ./node_modules/bower/bin/bower install
