sudo: required
language: node_js

node_js:
  - '4.4'

services:
  - docker

install:
  - npm install --loglevel=silent

script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm cache clean
  - npm run lint
  - npm run build
  - npm test
  - if [ $DOCKER_HUB_USERNAME ]; then docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD && docker build -t $DOCKER_IMAGE_NAME . && if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG; docker push $DOCKER_IMAGE_NAME; fi; fi

env:
  - DOCKER_IMAGE_NAME=swaggerapi/swagger-editor

deploy:
  on:
    tags: true
  provider: npm
  email: "apiteam@swagger.io"
  api_key:
    secure: G/bZcCrTPWYcLRrmFGMTxrNw6dOJkvijpjwprDieGarhwhY9Y2EZlzFIuLIKxE7Aht9W5P61Ic7tI48Akeb68GGtTDXTlut/BC6tDG0q5yXh9MoEerqrYmgd1KErT/szAQX+kdFAY+NDM9rov8o6H+iFNZBYvxf11dBBFoXv11Q=
