# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ApiDOM Editor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.8.x]

    steps:
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ steps.generate-token.outputs.token }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache npm cache files
      id: cache-npm-cache-files
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    - name: Cache Cypress binary
      id: cache-cypress-binary
      uses: actions/cache@v2
      with:
        path: cypress/cache
        key: cypress-binary-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies for apidom core
      if: |
          steps.cache-npm-cache-files.cache-hit != 'true' ||
          steps.cache-node-modules.cache-hit != 'true'
      run: npm ci
      working-directory: ./apidom
    - name: Build apidom core
      run: npm run build
      working-directory: ./apidom
    - name: Mark apidom core as built
      run: touch apidom-built
    - name: Install dependencies
      if: |
          steps.cache-npm-cache-files.cache-hit != 'true' ||
          steps.cache-node-modules.cache-hit != 'true' ||
          steps.cache-cypress-binary.outputs.cache-hit != 'true'
      run: npm ci
    - name: Unit tests
      run: npm test --watchAll=false
      env:
        CI: true
    # - name: E2E Tests - chrome headless
    #   id: cypress-run-ci
    #   uses: cypress-io/github-action@v2
    #   with:
    #     # we have already installed all dependencies above
    #     install: false
    #     browser: chrome
    #     wait-on: "http://localhost:3260"
    #     wait-on-timeout: 120
    #     headless: true
    #     start: npm run start-ci
    - name: Build app artifacts
      run: npm run build
    - name: Upload build artifacts (for GH pages)
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./build
    - name: Log in to DockerHub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_SB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SB_PASSWORD }}
    - name: Build docker image and push
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: smartbear/swagger-ide:latest 
    - name: Build local docker image without export
      if: github.ref != 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: smartbear/swagger-ide:pr

  deploy:
    name: Deploy to GH Pages
    if: github.ref == 'refs/heads/main'

    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Download built artifact from build job
      uses: actions/download-artifact@v2
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
        clean: true # Automatically remove deleted files from the deploy branch
