# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Swagger IDE build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# ApiDOM build system can utilize this setting
env:
  CPU_CORES: 2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@swagger-api"

      - name: Cache npm cache files
        id: cache-npm-cache-files
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Cache Cypress binary
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: cypress/cache
          key: cypress-binary-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint commit message
        if: github.ref != 'refs/heads/main' && github.actor != 'dependabot[bot]'
        run: git log -1 --pretty=format:"%s" | npx commitlint

      - name: Lint code
        run: npm run lint

      - name: Unit tests
        run: npm test
        env:
          CI: true

      - name: Build App artifacts
        run: npm run build:app

      - name: E2E Tests
        run: npm run cy:ci

      - name: Upload build artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build
